apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduling-config
  namespace: studymeet
data:
  PORT: "3000"
  HOST: "0.0.0.0"
  CORS_ORIGIN: "*"
  LIVEKIT_URL: "wss://helpmanager-cgkgdjae.livekit.cloud"
