apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduling-config
  namespace: studymeet
data:
  PORT: "3000"
  HOST: "0.0.0.0"
  CORS_ORIGIN: "https://study-meet.wjthinkbig.com,http://localhost:5174,http://localhost:5173"
  LIVEKIT_URL: "wss://helpmanager-cgkgdjae.livekit.cloud"
