apiVersion: v1
kind: Service
metadata:
  name: studymeet-scheduling
  namespace: studymeet
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: scheduling
  ports:
    - name: http
      port: 80
      targetPort: 3000
    - name: ws
      port: 3000
      targetPort: 3000
