kotlin.code.style=official
android.useAndroidX=true
android.compileSdk=34
android.minSdk=24
android.targetSdk=34

# WebRTC
webrtc.version=1.0.0

# Kotlin
kotlin.version=1.9.21

# Gradle
org.gradle.configuration.cache=false
org.gradle.java.home=/Users/chales7/Library/Java/JavaVirtualMachines/openjdk-25.0.1/Contents/Home
